### ISSUE TITLE
Only works with version 3 of the GitLab API

### ISSUE THREAD

**Issue by kmccmk9** [Strider-CD/strider-gitlab#100]
I recommend this (for now) at least be added to the documentation. I just struggled for hours until I realized that it works when the API URL is v3 but not v4. This will confuse many other users as well since the "help" for the API Url redirects to the current up to date documentation from GitLab which no suggests v4 over v3.

**Comment by xgalen** [comment]
@kmccmk9  a PR with the info that you would like to find is welcome.

**Comment by knownasilya** [comment]
v2.0.0 of this lib should work with v4. Give it a try in Strider 2.4.1
