### ISSUE TITLE
webhook not working, gives 404 on post.

### ISSUE THREAD

**Issue by scottbert** [Strider-CD/strider-gitlab#109]
```
Gitlab CE 11.6.2
Strider 11.1.0
strider-gitlab 1.2.7
```

I'm running Strider proxied through Apache on a Fedora server. I can't get webhooks to work. I can see in the Apache logs that the post happens, but strider is returning a 404

Tried reinstalling the plugin, reinstalling strider, removing the site from cloudflare so it's just standalone apache and nothing I do seems to get the webhook to work correctly. Testing it from inside of Gitlab gives this warning:

```
Hook executed successfully but returned HTTP 404 <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot POST /<name>/<repo>/api/gitlab/webhook</pre> </body> </html>
```

And in my apache logs I can see

```
"POST /<name>/<repo>/api/gitlab/webhook HTTP/1.1" 404 193
```
Running this post in postman I can see it's hitting express by the headers

Running Strider in debug mode though I can't see anything in the log at all

I've run out of ideas. Can anyone help?

**Comment by knownasilya** [comment]
Try enabling logging for the webhooks `DEBUG=strider-gitlab:webhooks <commandtorunstrider>`

**Comment by scottbert** [comment]
I just tried this. I tailed the log, removed the webhook and added it again from the config page in Strider. Still nothing in strider's log. GET gives me an error but POST nothing at all - it's almost like it's not even reaching strider, yet other posts are working fine.

**Comment by knownasilya** [comment]
What version of Gitlab API?

**Comment by scottbert** [comment]
Tried both v3 and v4 - it's currently v4

**Comment by knownasilya** [comment]
@scottbert I don't think v4 is supported at this time (yet). Are there any logs with v3?

**Comment by scottbert** [comment]
Not that I can see

**Comment by scottbert** [comment]
According to gitlab's docs, v3 was removed in GitLab 11.

**Comment by knownasilya** [comment]
v2.0.0 of this lib should work with v4. Give it a try in Strider 2.4.1
