### ISSUE TITLE
Create GitLab web hook when adding repository to Strider

### ISSUE THREAD

**Issue by marcuspoehls** [Strider-CD/strider-gitlab#18]
Currently you have to manually configure a GitLab web hook to trigger Strider builds on `[push, tag, issue, merge]` events. This could be automated and hooks should be created manually while adding a repo to Strider.

GitLab offers a respective web hook API: http://doc.gitlab.com/ee/api/projects.html#add-project-hook

**Comment by marcuspoehls** [comment]
I don’t want to delegate this task :) will submit a PR adding this feature. If somebody else is already working at this functionality, just reach out :point_up:

**Comment by marcuspoehls** [comment]
This is already working again due to the great work of @oliversalzburg in https://github.com/Strider-CD/strider-gitlab/pull/17! Thanks man!

**Comment by oliversalzburg** [comment]
This *should* have worked before as well. If it wasn't working for you with a slightly older version of the plugin, then there might be another issue.

**Comment by marcuspoehls** [comment]
It didn’t work for our deployment before your update. I didn’t dig deeper to find the reason since I saw your changes in the morning and stopped working on it.

**Comment by marcuspoehls** [comment]
The deployment key setup was working, web hooks not.

**Comment by oliversalzburg** [comment]
Interesting. Well, good to hear that it's working :)
