### ISSUE TITLE
Should sendJob return true, because if we reach that point in the code, the job has been successfully created?

### ISSUE THREAD

**Issue by saraf** [Strider-CD/strider-gitlab#30]
Question about webhooks in the gitlab provider - what is the intent of 
https://github.com/Strider-CD/strider-gitlab/blob/master/lib/webhooks.js#L47

Because, sendJob [does not return anything] (https://github.com/Strider-CD/strider-gitlab/blob/master/lib/webhooks.js#L110-L112), so even if a job was created successfully, *we still get __undefined__ as a result*, and __"webhook received, but no branches matched or branch is not active" is logged to the console__ - https://github.com/Strider-CD/strider-gitlab/blob/master/lib/webhooks.js#L102-L108

**Comment by knownasilya** [comment]
Looks like that needs some fixing..

**Comment by saraf** [comment]
will do.

**Comment by saraf** [comment]
Fixed. Closing.
