### ISSUE TITLE
how to enable it?

### ISSUE THREAD

**Issue by capaj** [Strider-CD/strider-gitlab#36]
Hi, I am quite new to strider, so maybe there is something trivial that I am missing, but how do you enable this plugin?

I have installed strider, installed this plugins, restarted strider but I can't see anything related to gitlab. My strider interface looks exactly like it was before I installed the plugin. Only thing that is changed is that in plugins section, I can see installed gitlab plugin version `1.1.3`. Is there anything like a switch to turn the plugin on?

**Comment by oliversalzburg** [comment]
Go to the **Projects** section. There should be a tab with your GitLab username on it. There you'll be able to import projects from your GitLab account.

**Comment by capaj** [comment]
@oliversalzburg do I have to set up enviromental variables? because I only have github and bitbucket there

**Comment by oliversalzburg** [comment]
@capaj No, it should work out-of-the-box. Are there any errors logged in strider?

**Comment by llacroix** [comment]
Same problem here

**Comment by oliversalzburg** [comment]
@llacroix Then I have the same question for you :)

**Comment by llacroix** [comment]
Well no errors, nothing, not on the server, not in the web console. I've been able to my project using manual setup and pointing the webhooks using the gitlab api... (all done manually) So things seems to work but the tab isn't coming on by itself.

**Comment by knownasilya** [comment]
Did you update the plugins from the Admin > Plugins section?

**Comment by llacroix** [comment]
At first, no.. then uninstalled from there and installed from there.

**Comment by mastertinner** [comment]
I'm having the same problem... Latest strider (`1.7.5`) and latest version of the plugin (`1.1.3`). There were no errors during `npm start`. It would be nice if there was a "Getting Started" in the `README.md`.

**Comment by mastertinner** [comment]
@capaj & @llacroix Ila, I just figured it out: You first need to click your e-mail address in the top right corner, then click "Account", then go to the "Gitlab" section and add your account there. After that, the Gitlab tab should show up in the "Projects" section. From my side, this issue can therefore be closed.

**Comment by knownasilya** [comment]
Will look more into this.

**Comment by knownasilya** [comment]
@mastertinner would appreciate it if you could submit a PR updating the README with this last step.

**Comment by mastertinner** [comment]
Done: #39

**Comment by llacroix** [comment]
@mastertinner yes fixed it. Didn't know about this menu.

**Comment by meric426** [comment]
Fixed in https://github.com/Strider-CD/strider-gitlab/pull/39. Thanks @mastertinner
