### ISSUE TITLE
Can't see all repos

### ISSUE THREAD

**Issue by mastertinner** [Strider-CD/strider-gitlab#40]
Somehow I can't see all of my Gitlab repos in the Strider GUI... Any idea why I can see most of them but not all? I have the role "Owner" on the ones I can't see.

**Comment by knownasilya** [comment]
Did you click the refresh repos button?

**Comment by mastertinner** [comment]
Yes, I did.
Also: I can't see all groups I am part of... I am part of 6 groups but can only see 5 of them. I am "Owner" of the group I can't see.

**Comment by mastertinner** [comment]
FYI: I'm using strider `1.7.5`, strider-gitlab `1.1.3` and `v3` of the Gitlab API.

**Comment by mastertinner** [comment]
I think I've figured out what the problem is here. I have more than 100 repos which I have access to. The API however, limits to `per_page: 100`. So I guess we would need to iterate over the pages here... What do you think, @knownasilya?

https://github.com/gitlabhq/gitlabhq/tree/master/doc/api#pagination

**Comment by knownasilya** [comment]
That was my thought as well. Seems like the pagination was never implemented in the gitlab provider. Think you could tackle a PR for this? I can review and help out if needed.

**Comment by mastertinner** [comment]
I'll give it a shot :) thanks for your quick replies!

**Comment by mastertinner** [comment]
Done: #42
Please merge or provide me with feedback :)

**Comment by mastertinner** [comment]
From my point of view, this issue can be closed. Thanks for the great support!
