### ISSUE TITLE
add project with 500

### ISSUE THREAD

**Issue by terminatorheart** [Strider-CD/strider-gitlab#46]
i followed tutorial here 
https://futurestud.io/blog/strider-how-to-connect-with-gitlab-and-run-tests-automatically
 and when i reach the step add project, i got this error
```Error creating project for repo terminator/tmgc_admin: {"results":[],"status":"error","errors":[{"code":500,"reason":"Failed to setup repo: Unprocessable Entity"}]}```
so i print error message step by step, and i find gitlab hook create api return 422 with error msg "invalid url",  at last, i find the problem occured by
something in 'strider-gitlab/lib/webapp.js'(line 106)
```var url = hostname + '/' + project.name + '/api/gitlab/webhook```
in there, url has no protocol, if i add a protocol prefix like "http://", thing looks ok

addition info : my gitlab server has no domain, i visit it by ip and port

**Comment by knownasilya** [comment]
So adding the protocol fixes the issue? Make sure to set `SERVER_NAME=http://ip:port`.

**Comment by terminatorheart** [comment]
got it, thanks
