### ISSUE TITLE
Configuration of Web Hooks

### ISSUE THREAD

**Issue by jmlegaza** [Strider-CD/strider-gitlab#6]
Hi

I'm trying to configure the Web Hooks between GitLab and Strider but there is no possible.

When I configure the Hook on GitLab, what is the right route to Strider?

Thanks in advance

Regards

**Comment by cerw** [comment]
Is this project still active? I have same quetsions thanks

**Comment by oliversalzburg** [comment]
@jmlegaza @cerw There really shouldn't be anything that you need to do. Once you add a project from this provider, it should add the web hook by itself through the GitLab API.

If that is not happening, then this is a bug.

Please let me know if you're still experiencing this problem with the latest version. Thanks.

**Comment by cerw** [comment]
I gave up and moved to phptesting.org thanks anyway
