### ISSUE TITLE
Not all namespaces are visible

### ISSUE THREAD

**Issue by pajtai** [Strider-CD/strider-gitlab#71]
We have quite a few namespaces and only the first 33 (alphabetically up to the beginning letter "m") are visible at /projects.

Is there any way to get to the next page of namespaces?

**Comment by oliversalzburg** [comment]
So, is this a UI issue or are really not all projects retrieved?

**Comment by knownasilya** [comment]
Their api is paginated.

**Comment by oliversalzburg** [comment]
@knownasilya Yeah, but as I understand the source of this project, that's generally supported.

**Comment by knownasilya** [comment]
Strider v2.4.1 now has support for "only show me projects I'm a member of", that might be helpful for this. I think ultimately I'll add a search feature.
