### ISSUE TITLE
Unable to save account

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider-gitlab#8]
I'm trying to configure a Gitlab account in our Strider instance, but I always the the error "Unable to save account".

The log only shows a 404:

    PUT /api/account/gitlab/0 404 4.120 ms - 33

I've just set up this Strider instance from git moments ago, so everything should be up-to-date.

**Comment by oliversalzburg** [comment]
Worked after I checked out v1.6.6. master was also having trouble deleting Bitbucket account.

**Comment by oliversalzburg** [comment]
Seems like something is missing in https://github.com/Strider-CD/strider/commit/7be067795b5bdcdc25d124e65f9fd68c5dfa5501. @knownasilya is it possible that the new API routes are never registered?

**Comment by knownasilya** [comment]
@oliversalzburg yes that would do it :+1: Want to submit a PR?

**Comment by oliversalzburg** [comment]
@knownasilya Sadly, I don't understand the code well enough :(

**Comment by knownasilya** [comment]
@oliversalzburg ok will send a fix.

**Comment by oliversalzburg** [comment]
Awesome :)

**Comment by knownasilya** [comment]
Fixed by 354ea67bd45adfcb616a8cb3d2ec1d186eb5fb82
